### PR TITLE
Update v2.11.149685

### PR DESCRIPTION
**Pull request by Leopard20**

### CODE REVIEW

**Comment by dedmen** [comment]
Hard to check changes when there are duplicates with #266

**Comment by Leopard20** [comment]
Yeah I based the branch on that one 😓

**Comment by Leopard20** [comment]
I'll remake it I guess

**Comment by dedmen** [comment]
Just update the branch :poutcat:

**Comment by Leopard20** [comment]
I had no idea what I was doing (it kept saying it has conflicts) but I guess it finally worked 😓

**Comment by Leopard20** [comment]
omg I fucking hate Git Lens. That retarded extension keeps pushing to upstream instead of origin (it had happened before). Fucking piece of garbage.

**Pull request closed without merging**
