### PR TITLE
Update 1.92 pointerlist

### PR DESCRIPTION
**Pull request by dedmen**

### CODE REVIEW

**Comment by dedmen** [comment]
1.94
https://community.bistudio.com/wiki/getResolution

**Comment by PabstMirror** [comment]
`count getResolution` = 6 on Version: 1.94.145903

**Comment by dedmen** [comment]
will have to add a condition on that then

**Comment by dedmen** [comment]
setBehaviour was broken if you passed a object :D oops, fixed now

**Pull request merged**
