### PR TITLE
Added checkVisibility

### PR DESCRIPTION
**Pull request by tbeswick96**
I couldn't find an implementation for [checkVisibility](https://community.bistudio.com/wiki/checkVisibility), so I added it. Just copied implementation from intersects, hope it's ok.

### CODE REVIEW

**Comment by dedmen** [comment]
@jonpas Did you check that we really don't have it yet? Conversion coverage script shouldn't have missed this.

**Comment by tbeswick96** [comment]
@dedmen I triple checked there was no implementation for it, but there was an assignment, definition, and declaration for the engine function

**Comment by jonpas** [comment]
GitHub search didn't find it, maybe it's somewhere in the comment?

**Comment by dedmen** [comment]
https://github.com/intercept/intercept/blob/cd971f2e027c9f8bd106fbcdd38a54882c4c5a3d/src/client/intercept/client/sqf/uncategorized.cpp#L218 
Found it. Another Why the F is this on "Don't implement"

**Comment by jonpas** [comment]
This is not under "don't implement", it's under ["investigate"](https://github.com/intercept/intercept/blob/cd971f2e027c9f8bd106fbcdd38a54882c4c5a3d/src/client/intercept/client/sqf/uncategorized.cpp#L160)

**Pull request merged**
